# Generated by Django 5.2 on 2025-04-10 16:13

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('dataviaggio', models.DateField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('multianno', models.BooleanField(blank=True, default=False, null=True)),
                ('multefoto', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.Immagine.set_path)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('road', models.CharField(blank=True, max_length=80, null=True)),
                ('exif', models.BooleanField(blank=True, default=False, null=True)),
                ('gps_location', models.BooleanField(blank=True, default=False, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('altezzaslm', models.FloatField(blank=True, null=True)),
                ('citta', models.CharField(blank=True, max_length=80, null=True)),
                ('nazione', models.CharField(blank=True, max_length=80, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('album_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'immagine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('rotation', models.IntegerField(blank=True, null=True)),
                ('exif', models.BooleanField(blank=True, default=False, null=True)),
                ('gps_location', models.BooleanField(blank=True, default=False, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('altezzaslm', models.FloatField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
                ('road', models.CharField(blank=True, max_length=80, null=True)),
                ('citta', models.TextField(blank=True, null=True)),
                ('nazione', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MediaFile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image2Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', related_query_name='aaa', to='home.album')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='immagini', related_query_name='bbb', to='home.immagine')),
            ],
            options={
                'db_table': 'image2album',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Media2Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediaalbums', to='home.album')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediamedia', to='home.mediafile')),
            ],
            options={
                'db_table': 'media2album',
                'managed': True,
            },
        ),
    ]
