# Generated by Django 5.2 on 2025-04-10 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immagine',
            old_name='album_id',
            new_name='first_album_id',
        ),
    ]
