# Generated by Django 5.2 on 2025-04-11 09:08

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_album_id_immagine_first_album_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='first_album_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=home.models.MediaFile.set_path),
        ),
    ]
